import { createContext, useState } from "react";

export const CoinsContext = createContext([])

const initialCoins ={
    USD:"Dólar Americano",
    EUR:"Euro",
    CNY:"Yuan Chinês",
    CAD:"Dólar Canadense",
    AED:"Dirham dos Emirados",
    AFN:"Afghani do Afeganistão",
    ALL:"Lek Albanês",
    AMD:"Dram Armênio",
    ANG:"Guilder das Antilhas",
    AOA:"Kwanza Angolano",
    ARS:"Peso Argentino",
    AUD:"Dólar Australiano",
    AZN:"Manat Azeri",
    BAM:"Marco Conversível",
    BBD:"Dólar de Barbados",
    BDT:"Taka de Bangladesh",
    BGN:"Lev Búlgaro/BGN:",
    BHD:"Dinar do Bahrein",
    BIF:"Franco Burundinense",
    BND:"Dólar de Brunei",
    BOB:"Boliviano",
    BRL:"Real Brasileiro",
    BRLT:"Real Brasileiro Turismo",
    BSD:"Dólar das Bahamas",
    BTC:"Bitcoin",
    BWP:"Pula de Botswana",
    BYN:"Rublo Bielorrusso",
    BZD:"Dólar de Belize",
    CHF:"Franco Suíço",
    CHFRTS:"Franco Suíço",
    CLP:"Peso Chileno",
    CNH:"Yuan chinês offshore",
    COP:"Peso Colombiano",
    CRC:"Colón Costarriquenho",
    CUP:"Peso Cubano",
    CVE:"Escudo cabo-verdiano",
    CZK:"Coroa Checa",
    DJF:"Franco do Djubouti",
    DKK:"Coroa Dinamarquesa",
    DOGE:"Dogecoin",
    DOP:"Peso Dominicano",
    DZD:"Dinar Argelino",
    EGP:"Libra Egípcia",
    ETB:"Birr Etíope",
    ETH:"Ethereum",
    FJD:"Dólar de Fiji",
    GBP:"Libra Esterlina",
    GEL:"Lari Georgiano",
    GHS:"Cedi Ganês",
    GMD:"Dalasi da Gâmbia",
    GNF:"Franco de Guiné",
    GTQ:"Quetzal Guatemalteco",
    HKD:"Dólar de Hong Kong",
    HNL:"Lempira Hondurenha",
    HRK:"Kuna Croata",
    HTG:"Gourde Haitiano",
    HUF:"Florim Húngaro",
    IDR:"Rupia Indonésia",
    ILS:"Novo Shekel Israelense",
    INR:"Rúpia Indiana",
    IQD:"Dinar Iraquiano",
    IRR:"Rial Iraniano",
    ISK:"Coroa Islandesa",
    JMD:"Dólar Jamaicano",
    JOD:"Dinar Jordaniano",
    JPY:"Iene Japonês",
    JPYRTS:"Iene Japonês",
    KES:"Shilling Queniano",
    KGS:"Som Quirguistanês",
    KHR:"Riel Cambojano",
    KMF:"Franco Comorense",
    KRW:"Won Sul-Coreano",
    KWD:"Dinar Kuwaitiano",
    KYD:"Dólar das Ilhas Cayman",
    KZT:"Tengue Cazaquistanês",
    LAK:"Kip Laosiano",
    LBP:"Libra Libanesa",
    LKR:"Rúpia de Sri Lanka",
    LSL:"Loti do Lesoto",
    LTC:"Litecoin",
    LYD:"Dinar Líbio",
    MAD:"Dirham Marroquino",
    MDL:"Leu Moldavo",
    MGA:"Ariary Madagascarense",
    MKD:"Denar Macedônio",
    MMK:"Kyat de Mianmar",
    MNT:"Mongolian Tugrik",
    MOP:"Pataca de Macau",
    MRO:"Ouguiya Mauritana",
    MUR:"Rúpia Mauriciana",
    MVR:"Rufiyaa Maldiva",
    MWK:"Kwacha Malauiana",
    MXN:"Peso Mexicano",
    MYR:"Ringgit Malaio",
    MZN:"Metical de Moçambique",
    NAD:"Dólar Namíbio",
    NGN:"Naira Nigeriana",
    NGNI:"Naira Nigeriana",
    NGNPARALLEL:"Naira Nigeriana",
    NIO:"Córdoba Nicaraguense",
    NOK:"Coroa Norueguesa",
    NPR:"Rúpia Nepalesa",
    NZD:"Dólar Neozelandês",
    OMR:"Rial Omanense",
    PAB:"Balboa Panamenho",
    PEN:"Sol do Peru",
    PGK:"Kina Papua-Nova Guiné",
    PHP:"Peso Filipino",
    PKR:"Rúpia Paquistanesa",
    PLN:"Zlóti Polonês",
    PYG:"Guarani Paraguaio",
    QAR:"Rial Catarense",
    RON:"Leu Romeno",
    RSD:"Dinar Sérvio",
    RUB:"Rublo Russo",
    RUBTOD:"Rublo Russo",
    RUBTOM:"Rublo Russo",
    RWF:"Franco Ruandês",
    SAR:"Riyal Saudita",
    SCR:"Rúpias de Seicheles",
    SDG:"Libra Sudanesa",
    SDR:"DSE",
    SEK:"Coroa Sueca",
    SGD:"Dólar de Cingapura",
    SOS:"Shilling Somaliano",
    STD:"Dobra São Tomé",
    SVC:"Colon de El Salvador",
    SYP:"Libra Síria",
    SZL:"Lilangeni Suazilandês",
    THB:"Baht Tailandês",
    TJS:"Somoni do Tajiquistão",
    TMT:"TMT",
    TND:"Dinar Tunisiano",
    TRY:"Nova Lira Turca",
    TTD:"Dólar de Trinidad",
    TWD:"Dólar Taiuanês",
    TZS:"Shilling Tanzaniano",
    UAH:"Hryvinia Ucraniana",
    UGX:"Shilling Ugandês",
    USDT:"Dólar Americano",
    UYU:"Peso Uruguaio",
    UZS:"Som Uzbequistanês",
    VEF:"Bolívar Venezuelano",
    VND:"Dong Vietnamita",
    VUV:"Vatu de Vanuatu",
    XAF:"Franco CFA Central",
    XAGG:"XPrata",
    XBR:"Brent Spot",
    XCD:"Dólar do Caribe Oriental",
    XOF:"Franco CFA Ocidental",
    XPF:"Franco CFP",
    XRP:"XRP",
    YER:"Riyal Iemenita",
    ZAR:"Rand Sul-Africano",
    ZMK:"Kwacha Zambiana",
    ZWL:"Dólar Zimbabuense",
}

export const CoinsProvider = ({children})=>{
    const [coins, setCoins] = useState(initialCoins)

    return(
        <CoinsContext.Provider value={{coins, setCoins}}>
            {children}
        </CoinsContext.Provider>
    )
}